name: Fetch Google Sheet TSV and Convert to JSON

on:
  schedule:
    - cron: '0 0 * * *'   # Every day at midnight UTC
  push:
    paths:
      - '.github/workflows/fetch-data-sheet.yml'
      - '.github/scripts/tsv-to-json.ts'
  workflow_dispatch:      # Manual trigger from GitHub UI

jobs:
  convert-tsv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc .github/scripts/tsv-to-json.ts

      - name: Run compiled TSV to JSON script
        run: node .github/scripts/tsv-to-json.js
        env:
          TSV_URL: ${{ secrets.GOOGLE_SHEET_TSV_URL }}

      - name: Commit and push updated JSON
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add public/data/sheet-data.json
          git commit -m 'chore: update sheet-data.json from TSV' || echo "No changes to commit"
          git push